### ISSUE TITLE
Question: Countdown timer with Notificaition

### ISSUE THREAD

**Issue by randallmlough** [caseymrm/menuet#13]
I'm looking to create a simple countdown timer that will notify a user when the countdown is complete. Is it possible for this app to notify the users? 

Edit: Is this the library I would want for user notifications? https://github.com/caseymrm/go-pmset

Second question: Do all options have to be pre set or can it also take user input? I'm looking for a way to allow a user (me) to create specific timers to countdown from ( 32min or 30min 03 seconds, etc.)

**Comment by caseymrm** [comment]
Hi Randall, the library has two ways of notifying users- there's `menuet.App().Notification()` which shows a passive alert, or you can pop up a dialog with `menuet.App().Alert()`- if you run the "catalog" app you can see examples of both.

The only text input currently is part of the Alert system- they can have `Input`s where users can enter strings. Other than that you'd be looking at making a dropdown with common times. I'm interested in adding more sophisticated input options in the menu, but not sure when I'll get to them- let me know if you have any ideas.

**Comment by randallmlough** [comment]
Thanks for the reply. I looked at the catalog & weather example and see how their being implemented to fit my needs.

But I did build the catalog example (using make to create an Catalog.app), but I couldnt get any notification menu options to work. Is there anything special I have to do there?

Also, when I run the make file the script executes and appears to create all the necessary stuff, but the script never exits (seems like it's in a waiting state). I have to manually exit the operation `ctrl + c`. Is that the desired action?

**Comment by caseymrm** [comment]
Notifications are a bit tricky- I think the app may need to be signed for notifications to work, which is one of the reason I check in binaries to the repo. Let me see if I need to re-sign it or something. My cert may have expired, and there have been a couple of new versions of xcode since I built those binaries. Alerts are much simpler to get working if they handle your use case.

Yes, if you just run "make" it is using the "make run" rule, which runs the program and doesn't return until you hit quit from the menu. "make sign" will just build the app, generate the plist, and codesign it if you don't want to actually run it.
